dashboards/appTracker/applications/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.fields.choices import SelectField
from wtforms.fields.simple import SubmitField, URLField
from wtforms.validators import DataRequired


class NewApplication(FlaskForm):
    company_name = StringField("Company Name", validators=[DataRequired()])
    position_name = StringField("Position Name", validators=[DataRequired()])
    source = SelectField(
        "Source",
        choices=[
            ("LinkedIn", "LinkedIn"),
            ("Handshake", "Handshake"),
            ("Company Website", "Company Website"),
            ("Indeed", "Indeed"),
            ("Other", "Other"),
        ],
    )
    link = URLField("URL", validators=[])
    addr1 = StringField("Street Address", validators=[])
    addr2 = StringField("City Address", validators=[])

    submit = SubmitField("Add Application")


class EditApplication(FlaskForm):
    company_name = StringField("Company Name", validators=[DataRequired()])
    position_name = StringField("Position Name", validators=[DataRequired()])
    source = SelectField(
        "Source",
        choices=[
            ("LinkedIn", "LinkedIn"),
            ("Handshake", "Handshake"),
            ("Company Website", "Company Website"),
            ("Indeed", "Indeed"),
            ("Other", "Other"),
        ],
    )
    link = URLField("URL", validators=[])
    addr1 = StringField("Street Address", validators=[])
    addr2 = StringField("City Address", validators=[])
    status = SelectField(
        "Status",
        choices=[
            ("Initialized", "Initialized"),
            ("Applied", "Applied"),
            ("Accepted", "Accepted"),
            ("Rejected", "Rejected"),
        ],
    )

    submit = SubmitField("Apply Changes")


class EditNotes(FlaskForm):
    notes = StringField("Notes", validators=[DataRequired()])

    submit = SubmitField("Edit Notes")

dashboards/appTracker/applications/routes.py
from flask import Blueprint, send_from_directory
from flask import redirect, url_for, render_template, flash, request
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from flask_login import current_user
from dashboards.appTracker.applications.forms import (
    EditNotes,
    NewApplication,
    EditApplication,
)
from dashboards.appTracker.events.routes import deleteEvent
from dashboards.models import Application, Tracker, Event
from dashboards.appTracker.filters.filters import to_name, hasCoverLetter
from dashboards import db, executor, login_manager
from datetime import datetime
import secrets
from resumes import render
import shutil
import os

applications = Blueprint("applications", __name__)
default_breadcrumb_root(applications, ".appTracker.tracker")


@applications.before_request
def restrict_applications_to_users():
    if not current_user.is_authenticated:
        return redirect(url_for(login_manager.login_view))


@applications.route("/<tracker_nameid>/")
@register_breadcrumb(applications, ".", "Tracker")
def oneTracker(tracker_nameid):
    trackerName = to_name(tracker_nameid)
    correctTracker = Tracker.query.filter_by(name=trackerName).first_or_404()
    return render_template(
        "appTracker/tracker.html",
        title="Application Tracker - " + correctTracker.name,
        tracker=correctTracker,
    )


@applications.route("/<tracker_nameid>/add_new", methods=["GET", "POST"])
@register_breadcrumb(applications, ".add_new", "Add New Application")
def addNewApplication(tracker_nameid):
    form = NewApplication()
    if form.validate_on_submit():
        correctTracker = Tracker.query.filter_by(
            name=to_name(tracker_nameid)
        ).first_or_404()
        coverletter_file = secrets.token_hex(10) + ".pdf"
        application = Application(
            company_name=form.company_name.data,
            position_name=form.position_name.data,
            source=form.source.data,
            link=form.link.data,
            status="Initialized",
            coverletter=coverletter_file,
            addr1=form.addr1.data,
            addr2=form.addr2.data,
            of_tracker=correctTracker.tracker_id,
        )
        db.session.add(application)
        db.session.commit()
        firstHistory = Event(
            desc=f"Initialized application for {form.company_name.data}",
            from_me=True,
            action_necessary=True,
            date=datetime.now(),
            of_application=application.application_id,
        )
        db.session.add(firstHistory)
        db.session.commit()
        executor.submit(createCoverLetter, coverletter_file, application)
        flash(f"New Application added for {form.company_name.data}!", "success")
        return redirect(
            url_for("applications.oneTracker", tracker_nameid=tracker_nameid)
        )
    return render_template(
        "appTracker/new_application.html",
        title="Application Tracker - " + "New Application",
        form=form,
    )


@applications.route("/<tracker_nameid>/<app_id>/edit", methods=["GET", "POST"])
@register_breadcrumb(applications, ".edit", "Edit Application")
def editApplication(tracker_nameid, app_id):
    currentApplication = Application.query.filter_by(
        application_id=app_id
    ).first_or_404()
    form = EditApplication()
    if form.validate_on_submit():
        deleteCoverLetter(currentApplication)
        coverletter_file = secrets.token_hex(10) + ".pdf"
        currentApplication.company_name = form.company_name.data
        currentApplication.position_name = form.position_name.data
        currentApplication.source = form.source.data
        currentApplication.link = form.link.data
        currentApplication.status = form.status.data
        currentApplication.coverletter = coverletter_file
        currentApplication.addr1 = form.addr1.data
        currentApplication.addr2 = form.addr2.data
        db.session.commit()
        executor.submit(createCoverLetter, coverletter_file, currentApplication)
        flash(
            f"Application for {currentApplication.company_name} has been updated!",
            "success",
        )
        return redirect(
            url_for("applications.oneTracker", tracker_nameid=tracker_nameid)
        )
    elif request.method == "GET":
        form.company_name.data = currentApplication.company_name
        form.position_name.data = currentApplication.position_name
        form.source.data = currentApplication.source
        form.link.data = currentApplication.link
        form.status.data = currentApplication.status
        form.addr1.data = currentApplication.addr1
        form.addr2.data = currentApplication.addr2
    return render_template(
        "appTracker/edit_application.html",
        title="Application Tracker - " + "Edit Application",
        form=form,
    )


@applications.route("/tracker/<tracker_nameid>/<app_id>/delete", methods=["GET"])
def deleteApplication(tracker_nameid, app_id):
    currentApplication = Application.query.filter_by(
        application_id=app_id
    ).first_or_404()
    deleteCoverLetter(currentApplication)
    for event in currentApplication.event_history:
        deleteEvent(tracker_nameid, app_id, event.event_id)
    db.session.delete(currentApplication)
    db.session.commit()
    flash("This application has been deleted", "success")
    return redirect(url_for("applications.oneTracker", tracker_nameid=tracker_nameid))


@applications.route(
    "/tracker/<tracker_nameid>/<app_id>/editNotes", methods=["GET", "POST"]
)
@register_breadcrumb(applications, ".editNotes", "Edit Notes")
def editNotes(tracker_nameid, app_id):
    currentApplication = Application.query.filter_by(
        application_id=app_id
    ).first_or_404()
    form = EditNotes()
    if form.validate_on_submit():
        currentApplication.notes = form.notes.data
        db.session.commit()
        flash(
            f"Notes for {currentApplication.company_name} has been updated!",
            "success",
        )
        return redirect(
            url_for(
                "events.oneApplication", tracker_nameid=tracker_nameid, app_id=app_id
            )
        )
    elif request.method == "GET":
        form.notes.data = currentApplication.notes
    return render_template(
        "appTracker/edit_notes.html",
        title="Application Tracker - " + "Edit Notes",
        form=form,
    )


@applications.route("/tracker/<tracker_nameid>/<app_id>/coverletter")
def viewCoverLetter(tracker_nameid, app_id):
    currentApplication = Application.query.filter_by(
        application_id=app_id
    ).first_or_404()
    if hasCoverLetter(currentApplication):
        return send_from_directory(
            directory="coverletters/",
            path=currentApplication.coverletter,
            as_attachment=True,
            attachment_filename=(
                f"coverletter_{currentApplication.company_name.lower()}.pdf"
            ),
        )
    else:
        return redirect(
            url_for(
                "applications.editApplication",
                tracker_nameid=tracker_nameid,
                app_id=app_id,
            )
        )


def createCoverLetter(path, app: Application):
    render.update_coverletter(app)
    shutil.move(
        os.path.join(os.path.dirname(__file__), "../../../resumes/coverletter.pdf"),
        os.path.join(os.path.dirname(__file__), f"../../coverletters/{path}"),
    )


def deleteCoverLetter(app):
    try:
        os.remove(
            os.path.join(
                os.path.dirname(__file__),
                f"../../coverletters/{app.coverletter}",
            )
        )
    finally:
        return


@applications.route("/tracker/<tracker_nameid>/resume")
def viewResume(tracker_nameid):
    return send_from_directory(
        directory="../resumes/",
        path="resume.pdf",
        as_attachment=True,
    )


@applications.route("/<tracker_nameid>/reloadCoverLetters")
def reloadCoverLetters(tracker_nameid):
    executor.submit(reloadAllCoverLetters, tracker_nameid)

    return redirect(url_for("applications.oneTracker", tracker_nameid=tracker_nameid))


def reloadAllCoverLetters(tracker_nameid):
    trackerName = to_name(tracker_nameid)
    currentTracker = Tracker.query.filter_by(name=trackerName).first_or_404()
    for app in currentTracker.applications:
        deleteCoverLetter(app)
        createCoverLetter(app.coverletter, app)

dashboards/appTracker/events/routes.py
from flask import Blueprint
from flask import redirect, url_for, render_template, flash, request
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from flask_login import current_user
from dashboards.appTracker.events.forms import NewEvent, EditEvent
from dashboards.appTracker.events.utils import updateStatus
from dashboards.models import Application, Event
from dashboards.appTracker.filters.filters import format_datetime
from dashboards import db, login_manager


events = Blueprint("events", __name__)
default_breadcrumb_root(events, ".appTracker.tracker.application")


@events.before_request
def restrict_events_to_users():
    if not current_user.is_authenticated:
        return redirect(url_for(login_manager.login_view))


@events.route("/<tracker_nameid>/<app_id>")
@register_breadcrumb(
    events,
    ".",
    "Application",
)
def oneApplication(tracker_nameid, app_id):
    correctApplication = Application.query.filter_by(
        application_id=app_id
    ).first_or_404()
    return render_template(
        "appTracker/application.html",
        title="Application Tracker - " + correctApplication.company_name,
        application=correctApplication,
    )


@events.route("/<tracker_nameid>/<app_id>/add_new", methods=["GET", "POST"])
@register_breadcrumb(events, ".add_new", "Add New Event")
def addNewEvent(tracker_nameid, app_id):
    form = NewEvent()
    print(type(form.date.data))
    if form.validate_on_submit():
        correctApplication = Application.query.filter_by(
            application_id=app_id
        ).first_or_404()
        event = Event(
            desc=form.desc.data,
            from_me=form.from_me.data,
            action_necessary=form.action_necessary.data,
            date=form.date.data,
            of_application=correctApplication.application_id,
        )
        updateStatus(correctApplication, form.desc.data)
        db.session.add(event)
        db.session.commit()
        flash(f"New Event added for {format_datetime(form.date.data)}!", "success")
        return redirect(
            url_for(
                "events.oneApplication", tracker_nameid=tracker_nameid, app_id=app_id
            )
        )
    return render_template(
        "appTracker/new_event.html",
        title="Application Tracker - " + "New Event",
        form=form,
    )


@events.route("/tracker/<tracker_nameid>/<app_id>/<event_id>", methods=["GET", "POST"])
@register_breadcrumb(events, ".edit", "Edit Event")
def editEvent(tracker_nameid, app_id, event_id):
    currentEvent = Event.query.filter_by(event_id=event_id).first_or_404()
    form = EditEvent()
    if form.validate_on_submit():
        correctApplication = Application.query.filter_by(
            application_id=app_id
        ).first_or_404()
        updateStatus(correctApplication, form.desc.data)
        db.session.commit()

        currentEvent.desc = form.desc.data
        currentEvent.from_me = form.from_me.data
        currentEvent.action_necessary = form.action_necessary.data
        currentEvent.date = form.date.data
        db.session.commit()
        flash(
            f"Event with {currentEvent.desc} has been updated!",
            "success",
        )
        return redirect(
            url_for(
                "events.oneApplication", tracker_nameid=tracker_nameid, app_id=app_id
            )
        )
    elif request.method == "GET":
        form.desc.data = currentEvent.desc
        form.from_me.data = currentEvent.from_me
        form.action_necessary.data = currentEvent.action_necessary
        form.date.data = currentEvent.date
    return render_template(
        "appTracker/edit_event.html",
        title="Application Tracker - " + "Edit Event",
        form=form,
    )


@events.route("/tracker/<tracker_nameid>/<app_id>/<event_id>/delete", methods=["GET"])
def deleteEvent(tracker_nameid, app_id, event_id):
    currentEvent = Event.query.filter_by(event_id=event_id).first_or_404()
    db.session.delete(currentEvent)
    db.session.commit()
    flash("This event has been deleted", "success")
    return redirect(
        url_for("events.oneApplication", tracker_nameid=tracker_nameid, app_id=app_id)
    )

dashboards/appTracker/trackers/routes.py
from flask import Blueprint
from flask import redirect, url_for, render_template, flash, request
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from flask_login import current_user
from dashboards.appTracker.trackers.forms import NewTracker, EditTracker
from dashboards.appTracker.applications.routes import deleteApplication
from dashboards.models import Tracker
from dashboards.appTracker.filters.filters import to_name, to_nameid
from dashboards import db, login_manager


trackers = Blueprint("trackers", __name__)
default_breadcrumb_root(trackers, ".appTracker")


@trackers.before_request
def restrict_trackers_to_users():
    if not current_user.is_authenticated:
        return redirect(url_for(login_manager.login_view))


@trackers.route("/")
@register_breadcrumb(trackers, ".", "Trackers")
def allTrackers():
    return render_template(
        "appTracker/trackers.html",
        title="Application Tracker - " + "Trackers",
        trackers=Tracker.query.all(),
    )


@trackers.route("/add_new", methods=["GET", "POST"])
@register_breadcrumb(trackers, ".add_new", "Add New Tracker")
def addNewTracker():
    form = NewTracker()
    if form.validate_on_submit():
        tracker = Tracker(name=to_name(to_nameid(form.name.data)), desc=form.desc.data)
        db.session.add(tracker)
        db.session.commit()
        flash(f"New Tracker added for {tracker.name}!", "success")
        return redirect(url_for("trackers.allTrackers"))
    return render_template(
        "appTracker/new_tracker.html",
        title="Application Tracker - " + "New Tracker",
        form=form,
    )


@trackers.route("/<tracker_nameid>/edit", methods=["GET", "POST"])
@register_breadcrumb(trackers, ".edit", "Edit Tracker")
def editTracker(tracker_nameid):
    currentTracker = Tracker.query.filter_by(
        name=to_name(tracker_nameid)
    ).first_or_404()
    form = EditTracker()
    if form.validate_on_submit():
        currentTracker.name = to_name(to_nameid(form.name.data))
        currentTracker.desc = form.desc.data
        db.session.commit()
        flash(f"Tracker {currentTracker.name} has been updated!", "success")
        return redirect(url_for("trackers.allTrackers"))
    elif request.method == "GET":
        form.name.data = currentTracker.name
        form.desc.data = currentTracker.desc
    return render_template(
        "appTracker/edit_tracker.html",
        title="Application Tracker - " + "Edit Tracker",
        form=form,
    )


@trackers.route("/tracker/<tracker_nameid>/delete", methods=["GET"])
def deleteTracker(tracker_nameid):
    currentTracker = Tracker.query.filter_by(
        name=to_name(tracker_nameid)
    ).first_or_404()
    for application in currentTracker.applications:
        deleteApplication(tracker_nameid, application.application_id)
    db.session.delete(currentTracker)
    db.session.commit()
    flash("This tracker has been deleted", "success")
    return redirect(url_for("trackers.allTrackers"))

dashboards/templates/appTracker/application.html
{% extends "layout.html" %}
{% block content %}
<div class=row>
    <div class="col">
        <h5><b>Company:</b> {{application.company_name}}, <b>Position:</b>
            {%if application.link %} <a href="{{application.link}}">{{application.position_name}}</a>
            {% else %} {{application.position_name}}
            {% endif %} <br>

            <b>Source: </b> {{application.source}}, <b>Status: </b> {{application.status}}
        </h5>
    </div>
    <div class="col-3 align-self-center" align="right">
        <a class="btn btn-success border border-dark"
            href="{{ url_for('events.addNewEvent', tracker_nameid = application.of_tracker | to_nameid_from_trackerid , app_id = application.application_id) }}">Add
            New Event <i class="bi bi-pencil-square"></i></a>
    </div>
</div>
<div class="row">
    <div class="col">
        <h5>
            <a
                href="{{ url_for('applications.editNotes', tracker_nameid = application.of_tracker | to_nameid_from_trackerid , app_id = application.application_id) }}">
                <b>Notes:</b>
            </a>
            {% if application.notes %}
            {{ application.notes }}
            {% endif %}
        </h5>
    </div>
    <div class="col-3 align-self-center" align="right">
        <a class="btn btn-warning btn-sm px-4 mx-2 border border-dark" style="position: relative; z-index: 2;"
            href="{{ url_for('applications.editNotes', tracker_nameid = application.of_tracker | to_nameid_from_trackerid , app_id = application.application_id) }}">
            Edit Notes <i class="bi bi-pencil-fill"></i></a>
    </div>
</div>
<br>
<div style="overflow-x:auto;">
    <table id="data" class="table table-sm table-hover">
        <thead>
            <tr>
                <th>Description</th>
                <th>From</th>
                <th>Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for event in application | sortedEvents %}
            <tr>
                <td>{{ event.desc }}</td>
                <td> {% if event.from_me %} Me {% else %} Them {% endif %}</td>
                <td>{{ event.date|formatdatetime }}</td>
                <td align="right"><a class="btn btn-warning btn-sm px-4 mx-2 border border-dark"
                        href="{{url_for('events.editEvent', tracker_nameid = application.of_tracker | to_nameid_from_trackerid, app_id = application.application_id, event_id = event.event_id) }}">
                        <i class="bi bi-pencil-fill"></i> </a>
                    <a class="btn btn-danger btn-sm mx-2 border border-dark"
                        href="{{url_for('events.deleteEvent', tracker_nameid = application.of_tracker | to_nameid_from_trackerid, app_id = application.application_id, event_id = event.event_id) }}">
                        <i class="bi bi-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div> {% endblock content %}

dashboards/templates/appTracker/edit_event.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class=>Edit the event: "{{form.desc.data}}":</legend>
            <div class="form-group">
                {{form.desc.label(class="form-control-label")}}

                {% if form.desc.errors %}
                {{ form.desc(class="form-control form-control-lg is-invalid", autofocus="autofocus",
                onfocus="this.select()")}}
                <div class="invalid-feedback">
                    {% for error in form.desc.errors %}
                    <span>
                        {{ error }}
                    </span>
                    {% endfor%}
                </div>
                {% else %}
                {{form.desc(class="form-control form-control-lg", autofocus="autofocus",
                onfocus="this.select()")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.from_me.label(class="form-control-label")}} <br>

                {% if form.from_me.errors %}
                {% for subfield in form.from_me %}
                <tr class="form-control form-control-lg">
                    <td>{{ subfield }}</td>
                    <td>{{ subfield.label }}</td>
                </tr>
                {% endfor %}
                <div class="invalid-feedback">
                    {% for error in form.from_me.errors %}
                    <span>
                        {{ error }}
                    </span>
                    {% endfor%}
                </div>
                {% else %}
                {% for subfield in form.from_me %}
                <tr class="form-control form-control-lg">
                    <td>{{ subfield }}</td>
                    <td>{{ subfield.label }}</td>
                </tr>
                {% endfor %}

                {% endif %}
            </div>
            <div class="form-group">
                {{form.action_necessary.label(class="form-control-label")}} <br>

                {% if form.action_necessary.errors %}
                {% for subfield in form.action_necessary %}
                <tr class="form-control form-control-lg">
                    <td>{{ subfield }}</td>
                    <td>{{ subfield.label }}</td>
                </tr>
                {% endfor %}
                <div class="invalid-feedback">
                    {% for error in form.action_necessary.errors %}
                    <span>
                        {{ error }}
                    </span>
                    {% endfor%}
                </div>
                {% else %}
                {% for subfield in form.action_necessary %}
                <tr class="form-control form-control-lg">
                    <td>{{ subfield }}</td>
                    <td>{{ subfield.label }}</td>
                </tr>
                {% endfor %}

                {% endif %}
            </div>
            <div class="form-group">
                {{form.date.label(class="form-control-label")}}

                {% if form.date.errors %}
                {{ form.date(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.date.errors %}
                    <span>
                        {{ error }}
                    </span>
                    {% endfor%}
                </div>
                {% else %}
                {{form.date(class="form-control form-control-lg")}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info border border-dark")}}
        </div>
    </form>


</div>
{% endblock content %}

dashboards/templates/appTracker/tracker.html
{% extends "layout.html" %}
{% block content %}
<div class=row>
    <div class="col">
        <h5><b>Name:</b> {{tracker.name}}<br>
            <b>Description:</b> {{tracker.desc}}
        </h5>
    </div>
    <div class="align-self-center" align="right">
        <span class="col align-self-center">
            <a class="btn btn-secondary border border-dark"
                href="{{ url_for('applications.viewResume', tracker_nameid = tracker.name | to_nameid ) }}"><i
                    class="bi bi-download"></i> Resume </a></span>
        <span class="col align-self-center">
            <a class="btn btn-warning border border-dark"
                href="{{ url_for('applications.reloadCoverLetters', tracker_nameid = tracker.name | to_nameid ) }}"><i
                    class="bi bi-arrow-repeat"></i> Reload Cover Letters </a></span>
        <span class="col align-self-right">
            <a class="btn btn-success border border-dark"
                href="{{ url_for('applications.addNewApplication', tracker_nameid = tracker.name | to_nameid ) }}">Add
                New Application <i class="bi bi-pencil-square"></i>
            </a>
        </span>
    </div>
</div>
<br>
<div style="overflow-x:auto;">
    <table id="data" class="table table-sm table-hover">
        <thead>
            <tr>
                <th>Company Name</th>
                <th>Position</th>
                <th>Status</th>
                <th>Time Since</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="tracker-category-label bg-primary text-light">
                <th colspan="5">Action Required:</th>
            </tr>
            {{ display_applications(tracker.applications | sortApps | filterAppsNeedAction) }}
        </tbody>
        <tbody>
            <tr class="tracker-category-label bg-primary text-light">
                <th colspan="5">No Action Required:</th>
            </tr>
            {{ display_applications(tracker.applications | sortApps | filterAppsStillValid) }}
        </tbody>
        <tbody>
            <tr class="tracker-category-label bg-primary text-light">
                <th colspan="5">No Longer in Consideration:</th>
            </tr>
            {{ display_applications(tracker.applications | sortApps | filterAppsOther) }}
        </tbody>
    </table>
</div>
{% endblock content %}


{% macro display_applications(applications) %}
{% for app in applications %}
<tr style="position: relative;">
    <td>{{ app.company_name }}</td>
    <td>{%if app.link %} <a style="position: relative; z-index: 2;" href="{{app.link}}">{{app.position_name}}</a>
        {% else %} {{app.position_name}}
        {% endif %}</td>
    <td>{{app.status}}</td>
    <td>{{app | timeSinceUpdate | formattimedelta }}</td>
    <td align="right">
        {% if app | hasCoverLetter %}
        <a class="btn btn-secondary btn-sm px-3 mx-1 border border-dark" style="position: relative; z-index: 2;"
            href="{{url_for('applications.viewCoverLetter', tracker_nameid = tracker.name | to_nameid, app_id = app.application_id) }}"><i
                class="bi bi-download"></i> Cover Letter</a>
        {% endif %}
        <a class="btn btn-success btn-sm px-3 mx-1 border border-dark" style="position: relative; z-index: 2;"
            href="{{url_for('events.addNewEvent', tracker_nameid = tracker.name | to_nameid, app_id = app.application_id) }}"><i
                class="bi bi-plus-lg"></i> Add History</a>
        <a class="btn btn-primary btn-sm px-4 mx-1 border border-dark stretched-link"
            href="{{url_for('events.oneApplication', tracker_nameid = tracker.name | to_nameid, app_id = app.application_id) }}">View
            History</a>
        <a class="btn btn-warning btn-sm px-4 mx-1 border border-dark" style="position: relative; z-index: 2;"
            href="{{url_for('applications.editApplication', tracker_nameid = tracker.name | to_nameid, app_id = app.application_id) }}">
            <i class="bi bi-pencil-fill"></i> </a>
        <a class="btn btn-danger btn-sm mx-1 border border-dark" style="position: relative; z-index: 2;"
            href="{{url_for('applications.deleteApplication', tracker_nameid = tracker.name | to_nameid, app_id = app.application_id) }}">
            <i class="bi bi-trash"></i> </a>
    </td>
</tr>
{% endfor %}
{% endmacro %}

dashboards/templates/appTracker/trackers.html
{% extends "layout.html" %}
{% block content %}

<div class=row>
    <div class="col">
        <h5>Use this site to easily keep track of job applications. <br>
            It can track everything! Here are your existing trackers:
        </h5>
    </div>
    <div class="col-3 align-self-center" align="right">
        <a class="btn btn-success border border-dark" href="{{ url_for('trackers.addNewTracker') }}">Add New
            Tracker <i class="bi bi-pencil-square"></i></a>
    </div>
</div>
<br>
<div style="overflow-x:auto;">
    <table id="data" class="table table-sm table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th style="overflow: hidden;">Description</th>
                <th>Awaiting Action</th>
                <th>Total Applications</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for tracker in trackers %}
            <tr style="position: relative;">
                <td>{{ tracker.name }}</td>
                <td>
                    <div style="max-width: 400px; overflow: auto;">{{ tracker.desc }}</div>
                </td>
                <td>{{ tracker | totalAwaitingAction }}</td>
                <td>{{ tracker | totalApplications }}</td>
                <td align="right">
                    <div style="min-width: 375px;">
                        <a class="btn btn-primary btn-sm px-5 mx-2 border border-dark stretched-link"
                            href="{{ tracker.name | to_nameid }}">
                            View Applications </a>
                        <a class="btn btn-warning btn-sm px-4 mx-2 border border-dark"
                            style="position: relative; z-index: 2;"
                            href="{{ url_for('trackers.editTracker', tracker_nameid = (tracker.name | to_nameid) ) }}">
                            <i class="bi bi-pencil-fill"></i></a>
                        <a class="btn btn-danger btn-sm mx-2 border border-dark" style="position: relative; z-index: 2;"
                            href="{{ url_for('trackers.deleteTracker', tracker_nameid = (tracker.name | to_nameid) ) }}">
                            <i class="bi bi-trash"></i></a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}