dashboards/manageAcct/routes.py
from flask import Blueprint
from flask_breadcrumbs import default_breadcrumb_root
from flask_login import login_user, current_user, logout_user
from flask import render_template, redirect, url_for, request, flash
from dashboards import bcrypt
from dashboards.manageAcct.forms import LoginForm
from dashboards.models import User

manageAcct = Blueprint("manageAcct", __name__)
default_breadcrumb_root(manageAcct, ".")


@manageAcct.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return (
                redirect(next_page) if next_page else redirect(url_for("main.homepage"))
            )
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("manageAcct/login.html", title="Login", form=form)


@manageAcct.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.homepage"))

dashboards/templates/homepage.html
{% extends "layout.html" %}
{% block content %}

<div class="container application-grid">
    {{ display_widget("Application Tracker", "Track all of your job applications!", url_for('trackers.allTrackers') ) }}
</div>

{% endblock content %}

{% macro display_widget(name, desc, link) %}
<div class="card">
    <h3 class="card-header">{{ name }}</h3>
    <div class="card-body">
        <p class="card-text">{{ desc }}</p>
        <div>
            <a href="{{ link }}" class="btn btn-success px-5 stretched-link">Go!</a>
        </div>
    </div>
</div>
{% endmacro %}

dashboards/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css')}}" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Application Dashboard</title>
    {% endif %}
</head>

<body class="d-flex flex-column min-vh-100">
    <div class="header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navBar">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-brand mr-4">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('trackers.allTrackers') }}">Application
                                Tracker</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav me-auto">
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('manageAcct.logout') }}"> Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('manageAcct.login') }}"> Sign In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="main">

        <main class="container py-4">
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{category}}">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock content %}
        </main>
    </div>

    <div class=" footer mt-auto py-2 bg-primary">
        <div class="container">
            <div>
                <nav aria-label="breadcrumb">
                    <div>
                        <ol class="breadcrumb bg-primary my-2 p-0">
                            {% for breadcrumb in breadcrumbs %}
                            {% if not loop.last %}
                            <li class="breadcrumb-item"><a class="text-light" href="{{ breadcrumb.url }}">{{
                                    breadcrumb.text
                                    }}</a></li>
                            {% else %}
                            <li class=" breadcrumb-item active" aria-current="{{ breadcrumb.url }}"><a
                                    class="text-light" href="{{breadcrumb.url}}">{{
                                    breadcrumb.text }}</a></li>
                            {% endif %}
                            {% endfor %}
                        </ol>
                    </div>
                </nav>
            </div>

            <hr class="bg-light">

            <div class="text-light">
                <span>Collection of dashboards, courtesy of Connor McCarthy</span>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>